language: python
python:
  - "3.6.8"
sevices:
  - postgresql

# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip install poetry==1.1.4
install:
  - poetry install

before_script:
  - psql -c 'create database cocoman;' -U postgres
  - psql -c "create user root with password '1234';" -U postgres
# command to run tests
script:
  - poetry run pytest tests
  - pylint cocoman_recommender tests --errors-only